name: Amazon Daily Monitor Cron

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python Script
        env:
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python amazon_notifier.py

      - name: Save Database Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # 💡 履歴のすれ違いを事前に直すコマンド
          git pull origin main --rebase || echo "No changes to pull"
          
          if [ -f amazon_orders.db ]; then
            git add amazon_orders.db
            git commit -m "Update order history database [skip ci]" || exit 0
            git push origin main
          fi
