name: Amazon Inventory Bot

on:
  # 💡 手動でも実行できるように残しておきます
  workflow_dispatch: 
  
  # 💡 4時間に1回自動実行する設定を追加
  schedule:
    - cron: '0 */4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        env:
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          INVENTORY_GAS_URL: ${{ secrets.INVENTORY_GAS_URL }}
          DISCORD_WEBHOOK_SUMMARY: ${{ secrets.DISCORD_WEBHOOK_SUMMARY }}
        run: python amazon_inventory.py
